name       : poppler-data
version    : 0.4.10
release    : 3
source     :
    - https://poppler.freedesktop.org/poppler-data-0.4.10.tar.gz : 6e2fcef66ec8c44625f94292ccf8af9f1d918b410d5aa69c274ce67387967b30
license    :
    - BSD-3-Clause
    - GPL-2.0-only
    - MIT
component  : desktop.library
summary    : encoding data for the poppler PDF rendering library
description: |
    This package consists of encoding files for use with poppler. Thevencoding files are optional and poppler will automatically read them if they are present. When installed, the encoding files enables poppler to correctly render CJK and Cyrrilic properly.
patterns   : /usr/share/pkgconfig/poppler-data.pc
setup      : |
    %cmake_ninja
install    : |
    %ninja_install
