name       : poppler-data
version    : 0.4.11
release    : 4
source     :
    - https://poppler.freedesktop.org/poppler-data-0.4.11.tar.gz : 2cec05cd1bb03af98a8b06a1e22f6e6e1a65b1e2f3816cb3069bb0874825f08c
license    :
    - BSD-3-Clause
    - GPL-2.0-only
    - MIT
component  : desktop.library
summary    : encoding data for the poppler PDF rendering library
description: |
    This package consists of encoding files for use with poppler. Thevencoding files are optional and poppler will automatically read them if they are present. When installed, the encoding files enables poppler to correctly render CJK and Cyrrilic properly.
patterns   : /usr/share/pkgconfig/poppler-data.pc
setup      : |
    %cmake_ninja
install    : |
    %ninja_install
